### ISSUE TITLE
Peer feedback on big idea #2 (Andrew Carlson)

### ISSUE THREAD

**Issue by acarl005** [w201rdada/portfolio-rutikasb#5]
### Keep

In the intro, you've provided a good impetus for people to monitor their carbon footprint, and including an actual dollar cost ($300 billion) is even better! I think it was wise to mention the difficultly for people to change their habits. The goal is to raise awareness and achieve baby steps, which is very realistic. It's good that you list the stuff you'll be monitoring, as I get a good idea of how the data will be used to address the problem.

### Cut

I would try to avoid sentences which state things like, "I strongly believe that my tool can help with this cause." This is phrased as a subjective belief. Rather, you should be providing strong evidence for the promise and feasibility of your project. If you've done that well, then your claims about your own belief in your project become redundant, as they will become obvious from your factual support in the idea.

### Rearrange

The first mention of "climate change" in your proposal is in the third sentence, "the evidence of climate change is undeniable..." I didn't realize how the first two sentences about hurricanes were relevant until reaching the third sentence. I don't think it's common knowledge that climate change makes already naturally-occurring hurricanes worse. Maybe you could begin that paragraph with the mention that climate change makes natural disasters worse.

### Add

I think you should discuss how the data is actually going to be collected, as this is is a potential window for bias. How will you know about the user's transportation habits, waste production, and food consumption? Will there be sensors of some sort? Will they need to manually enter the data? If they must report it themselves, are they going to be compliant (or even remember to enter all that information)? Will they bias the data somehow when they enter it (maybe they report more of the "good" behavior)? Do people even know about their water and power consumption?

How will you be deciding the ideal carbon footprint for each household? If you make recommendations about people's emissions, there presumably needs to be some benchmark. Will you be comparing to national averages per person in the household? What if someone needs more water because they have a garden? Will that be accounted for?

Try to add citations to any claims that aren't common knowledge. How did you come up with the "$300 billion"? You mention urging people to eat "organic food," but in my understanding the appeal  to organic food was for the good of one's own health, not climate change. I haven't yet heard of any reports about organic food and climate change. A citation for that would help.

Since the goal is to reduce climate change, I think the reader would like to see some justification for targeting the "environmentally cautious person." Is this person a significant contributor to the problem, and by how much? Is it more than the carbon footprint of industrial sources? It would be nice to see an upper bound for the impact of this tool if it was successful.

### Overall

It's a great idea, especially given the political context of the United States right now. The urgency of the problem is pretty clear. The design of your tool could be a little more clear.

**Comment by rutikasb** [comment]
Thanks for the feedback Andrew. I've re-written the introduction and have added references from NASA and other sources to strengthen the claim about natural disasters.  I agree with you on the concerns about manual inputs, but I don't really have a better solution than it for now.
