### ISSUE TITLE
Peer Feedback (Nathan Nam)

### ISSUE THREAD

**Issue by NathanNam** [w201rdada/portfolio-rutikasb#7]
In overall, I like the idea helping save the earth with small changes. I think you should keep the dollar amount you capture for the recent damages from these natural disasters. $300B is big enough to raise the awareness.

However, I think a link between these natural disasters and CO2 emissions is somewhat weak. It would be great if you can add some data to back up this link. In addition, I'm concerned that your app would require lots of user's manual inputs across the type and amount of energy they consume, recycling habits, diet types and so on, resulting in poor engagement from users.

Moreover, it would be great if you could mention a tangible impact of your app. For example, with 10% increase of alternative to driving, we are able to reduce X% of CO2 emissions. This would solidify your idea's effectiveness.

Thanks,
Nathan

**Comment by rutikasb** [comment]
Thanks for the feedback Nathan. I've added references from NASA and other sources to strengthen the claim about natural disasters.  I agree with you on the concerns about manual inputs, but I don't really have a better solution than it for now.
