### ISSUE TITLE
Peer Feedback (Marcus Chen)

### ISSUE THREAD

**Issue by fa-mc** [w201rdada/portfolio-rutikasb#8]
Generally, I like your idea to help people who want to be eco-friendly contribute to reduce the CO2 emission. I have a few humble suggestions.

1.	In the first paragraph, you tried to raise the importance of reducing CO2 emission by mentioning climate disasters. Could you provide some evidence / theory that can help connect those two things? Hurricanes and wildfires happen every year, it will be helpful to provide evidence showing how CO2 concentration aggravates the situation.
2.	Your idea requires the user to manually log a lot of data, and it is very difficult to get a precise estimation and can potentially cause privacy concerns. Maybe just focus on raising awareness rather than getting a precise estimation for each user (e.g. talk about how much CO2 emission can be reduced if a household do not use plastic water bottles based on average data, rather than trying to produce a precise estimation of CO2 emission based on the user’s input)?

**Comment by rutikasb** [comment]
Thanks for the feedback Marcus. I've added references from NASA and other sources that show climate change as the evidence for natural disasters.
